"""Deterministically generate the Phase 04 synthetic local drum sample bank.

These are sound-design assets, not participant recordings or empirical data. Running this script
recreates every WAV and its SHA-256 manifest.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import wave
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "assets" / "samples"
RATE = 44_100


def waveform(kind: str, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    duration = 0.24 if kind in ("hihat", "crash", "ride") else 0.18
    t = np.arange(int(RATE * duration), dtype=np.float64) / RATE
    if kind == "hihat":
        signal = rng.normal(0, 1, len(t)) * np.exp(-t * 34)
    elif kind in ("crash", "ride"):
        noise = rng.normal(0, 1, len(t))
        metallic = sum(np.sin(2 * np.pi * f * t) for f in (431, 677, 941, 1259))
        signal = (0.55 * noise + 0.12 * metallic) * np.exp(-t * (10 if kind == "crash" else 14))
    elif kind == "snare":
        signal = (0.75 * rng.normal(0, 1, len(t)) + 0.25 * np.sin(2 * np.pi * 185 * t)) * np.exp(-t * 28)
    else:
        freq = {"tom1": 190, "tom2": 150, "floor-tom": 105}[kind]
        phase = 2 * np.pi * (freq * t - 42 * t**2)
        signal = np.sin(phase) * np.exp(-t * 20)
    signal[0] = 0.0
    signal *= 0.75 / max(1e-12, float(np.max(np.abs(signal))))
    return signal.astype(np.float32)


def write_wav(path: Path, samples: np.ndarray) -> None:
    pcm = np.round(np.clip(samples, -1, 1) * 32767).astype("<i2")
    with wave.open(str(path), "wb") as out:
        out.setnchannels(1)
        out.setsampwidth(2)
        out.setframerate(RATE)
        out.writeframes(pcm.tobytes())


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    args.output.mkdir(parents=True, exist_ok=True)
    definitions = [
        ("synth-hihat-v1", "hihat", 401),
        ("synth-snare-v1", "snare", 402),
        ("synth-tom1-v1", "tom1", 403),
        ("synth-tom2-v1", "tom2", 404),
        ("synth-floor-tom-v1", "floor-tom", 405),
        ("synth-crash-v1", "crash", 406),
        ("synth-ride-v1", "ride", 407),
    ]
    entries = []
    for sample_id, kind, seed in definitions:
        filename = f"{sample_id}.wav"
        path = args.output / filename
        write_wav(path, waveform(kind, seed))
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        entries.append(
            {
                "sample_id": sample_id,
                "file": filename,
                "sha256": f"sha256:{digest}",
                "license_id": "CC0-1.0",
                "source": "procedurally generated by scripts/generate_sample_bank.py",
                "sample_rate_hz": RATE,
                "channels": 1,
            }
        )
    manifest = {
        "schema_version": "1.0",
        "asset_kind": "synthetic-audio-samples",
        "empirical_data": False,
        "samples": entries,
    }
    # newline="\n" keeps the tracked manifest LF on every platform (Windows would otherwise write CRLF).
    (args.output / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8", newline="\n"
    )
    print(f"generated {len(entries)} deterministic samples in {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
